language: node_js
node_js:
- v4
- v5
- v6
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
script:
  - npm test -- --serial
env:
  global:
  - CXX=g++-4.8
  - SENDGRID_KEY=sendgridKey
  - MASTER_KEY=masterKey
  - JWT_SECRET=jwtSecret
  matrix:
    secure: VENUZYhkDca7f++1vVJXTbezKs2mhof7UR2I6/Y0BT6JEQyjN3mHKmpO/GGhQhSCCTEmhU2IjqGxaq+e17pBuXlnIahlYMiSMGhfX8F1C2e+UH0+eA9JmEaCOp1XpnPQmq6px4AOZhsLAXCP8bLeTkFkZo8nUGzQyklTLxgePaB7BpLJ851LPhkPkGL4t9PnfrJkHey7bzTrLZqyhzD5voUQG5JiuWiOba/G3EzB2vzlXAfd8yV0NzUEfFhzqRhTlHtTjsjg61C3BWIvkV76xSW6Jj//P4BUr9np58YdeQ+ABJyZKolYqsBIE1xNAsByTGkwAlc+RnAG3hT7HNacxRkZ2nnvxaUbHwGt48ZdeRtGDoVDWr2ITe5nIISihr3d3Bt7Jaw6aGATUw+lm2wmijWjWdEwvfhXUErGMGIn1/Hx2AN+E6noP3+uogPSRg3vfiS4eqPYypZq0zfaXvH5Nl2z38xmvYUtOMAHnCA+UfaFL2xYnItZ09VOQ4z2R5j8S8QfwFhYULA6RWKUrKnvA7orZlbuEWc8q/LY8X9fVF1tJD94GpWrBc5w1PnFbMkgbFYgDC6R8NeGsi43LIs3UXOqe7YtiR6krfy8L24gzkJzgUgC+My7fZh1/iEO20zpk3Zg9pVwFFZ//uKDZq3RXbrhWfjTxaVAj+MC+TX1rCU=
