language: node_js
services: mongodb
node_js:
- '4'
- '6'
before_script:
- npm install -g gulp
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
env:
  secure: fVJRbEeUs7kjeMWo6sD4Ck2iRmXCzokOp/C7Zob3Ko6IzKiDYjvGbG6/vEGEH736RKa3/GVsOBxmPswVZV6Owj2+KAwtVwMIg8pTV2J3xAj2CDAV7leG9A0UcQIhP42s13sb7BySHIPlAjd7TtGFTIgTkJ5kkn8sEZpki6twVOLJO9XrHe7wSsXZ7LO4S/VZiYAYNCiSGIeD5wL1oYzjGUNp4V1MSUZKgXX3xj7J5See8lUT0dwC8ZmCxklJhIPzMerYK+kWeP6hYhQ1B5yJ+aZFD0KNdpLefWnAaEne5gDpiCeUlmVWce5W4qlnJIIJD4AzoXyLbuD/W/zxkl567KWxw5d7bkjFSm4Ev823pKQhw4XtWHP5S4ohR5THzNsxWoppj6lvVWYLRXrT67qF0h65fCetUb5ZoqQqMEcX4RYbewjyj9IfudOLheLx9eUlC9Q4S5Rs9jpyl8Kkhrm844kbWXVs/ya5/BnW67xpmtBbnzxX5cX5j3fQn3r5gSgn55RlB9hd1hUKc1NLgjTDw7E4WTH75FBmRvg+WUOEDHZniY1PyFFbXQ9LrXnA1sUb/A5oBI9vY3PfwZsfOZjcuCtgTMm3qgYdZPxycQwQm41lWpfCAHTZa3Ol1W7weXVDyLccPIuA4s4mFCkwOLCdegE3AMSg1dE+V9+MyEvI7UM=
